//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicGame.src.Models.Game
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameBuildingsTable
    {
        public int GameBuildingId { get; set; }
        public int GameBuildingType { get; set; }
        public string GameBuildingName { get; set; }
        public int GameBuildingHP { get; set; }
        public int GameBuildingAttack { get; set; }
        public int GameBuildingDefence { get; set; }
        public int GameBuildingGoldIncome { get; set; }
        public int GameBuildingGoldOutcome { get; set; }
        public int Capcatity { get; set; }
    }
}
