//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicGame.src.Models.Game
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameUnitTypeTable
    {
        public int GameUnitTypeId { get; set; }
        public string GameUnitTypeName { get; set; }
    }
}
