//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicGame.src.Models.Game
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameUnitsTable
    {
        public int GameUnitId { get; set; }
        public int GameUnitType { get; set; }
        public string GameUnitName { get; set; }
        public int GameUnitHP { get; set; }
        public int GameUnitAttack { get; set; }
        public int GameUnitDefence { get; set; }
        public int GameUnitGoldIncome { get; set; }
        public int GameUnitGoldOutcome { get; set; }
    }
}
