//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicGame.src.Models.Session
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionBasesTable
    {
        public int SessionBaseId { get; set; }
        public int SessionCoreId { get; set; }
        public int BuildingLevel { get; set; }
        public int WorkersNumber { get; set; }
        public int UniqueUpgrade { get; set; }
        public int AttackUpgrade { get; set; }
        public int DefenceUpgrade { get; set; }
        public int CapacityUpgrade { get; set; }
    }
}
