export interface CoreInfo 
{
    Money: number,
    CoreId: number,
    CoreMapId: number,
    BaseLevel: number,
    BaseCapacity: number,
    BaseHp: number,
    BaseAttack: number,
    BaseDefence: number,
    BaseWorkersCount: number,
    BaseType: number,
    BaseIncome: number,
    BaseOutcome: number,
    NumberOfWorkersInBase: number,
    Casern:boolean,
    GoldMining:boolean,
    DefenceTower:boolean,
    CasernLevel: number,
    CasernCapacity: number,
    CasernHp: number,
    CasernAttack: number,
    CasernDefence: number,
    CasernWarriorsCount: number,
    CasernAttackAircraftsCount: number,
    CasernType: number,
    CasernIncome: number,
    CasernOutcome: number,
    NumberOfWarriors: number,
    NumberOfAttackAircraft: number,
    DefenceTowerLevel: number,
    DefenceTowerCapacity: number,
    DefenceTowerHp: number,
    DefenceTowerAttack: number,
    DefenceTowerDefence: number,
    DefenceTowerType: number,
    NumberOfDefenceTower: number,
    GoldMiningLevel: number,
    GoldMiningCapacity: number,
    GoldMiningHp: number,
    GoldMiningAttack: number,
    GoldMiningDefence: number,
    GoldMiningType: number,
    GoldMiningIncome: number,
    GoldMiningOutcome: number,
    NumberOfWorkersInGoldMining: number
}