//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicGame.src.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRelationTable
    {
        public int RelationId { get; set; }
        public int UserId { get; set; }
        public int Relation { get; set; }
        public string List { get; set; }
    }
}
