//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicGameCommon
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFollowingTable
    {
        public int UserFollowingId { get; set; }
        public int UserId { get; set; }
        public int FollowingId { get; set; }
    }
}
