//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicGameCommon.Models.User
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFriendsTable
    {
        public int UserFriendId { get; set; }
        public int UserId { get; set; }
        public int FriendId { get; set; }
    }
}
